# Generated by Django 4.2.5 on 2023-09-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_time',
        ),
    ]
