# Generated by Django 4.2.5 on 2023-09-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product_id',
            new_name='product',
        ),
    ]
