# Generated by Django 4.2.5 on 2023-10-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_winner_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.product'),
        ),
    ]
