# Generated by Django 4.2.5 on 2023-10-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
