# Generated by Django 4.2.5 on 2023-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='prod_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
