# Generated by Django 4.2.5 on 2023-10-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_winner_prod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='prod_id',
        ),
        migrations.AlterField(
            model_name='winner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.product'),
        ),
    ]
