# Generated by Django 4.2.5 on 2023-12-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_winner_prod_id_alter_winner_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
